apiVersion: batch/v1
kind: CronJob
metadata:
  name: demojob
spec:
  schedule: "* * * * *" #	Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: demojob
              image: halfcoconut/hello-egg/demojob-live:v0.0.1
              imagePullPolicy: IfNotPresent
#              command:
#                - /bin/sh
#                - -c
#                - date; echo Hello!
          restartPolicy: OnFailure