// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/half-coconut/gocopilot/core-engine/interactive/events"
	"github.com/half-coconut/gocopilot/core-engine/interactive/grpc"
	"github.com/half-coconut/gocopilot/core-engine/interactive/ioc"
	"github.com/half-coconut/gocopilot/core-engine/interactive/repository"
	"github.com/half-coconut/gocopilot/core-engine/interactive/repository/cache"
	"github.com/half-coconut/gocopilot/core-engine/interactive/repository/dao"
	"github.com/half-coconut/gocopilot/core-engine/interactive/service"
)

// Injectors from wire.go:

func InitAPP() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, loggerV1)
	interactiveService := service.NewInteractiveService(interactiveRepository, loggerV1)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	server := ioc.InitGRPCxServer(loggerV1, interactiveServiceServer)
	client := ioc.InitKafka()
	interactiveReadEventConsumer := note.NewInteractiveReadEventConsumer(loggerV1, interactiveRepository, client)
	v := ioc.NewConsumers(interactiveReadEventConsumer)
	app := &App{
		server:    server,
		consumers: v,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitLogger, ioc.InitRedis, ioc.InitKafka)

var interactiveSvcProvider = wire.NewSet(service.NewInteractiveService, repository.NewCachedInteractiveRepository, dao.NewGORMInteractiveDAO, cache.NewRedisInteractiveCache)
