db:
#  dsn: "root:root@tcp(localhost:13316)/coreengine"
  dsn: "root:root@tcp(localhost:30002)/coreengine"

redis:
#  addr: "localhost:6379"
  addr: "localhost:30003"


kafka:
  addrs:
    - "localhost:9094"

etcd:
  endpoints:
    - "localhost:12379"

grpc:
  client:
    intr:
      name: "interactive"
      secure: false

# 这个是流量控制的 client 的配置
#grpc:
#  client:
#    intr:
#      addr: "localhost:8090"
#      secure: false
#      threshold: 100

# 日志配置
log:
  disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件和行号
  disable-stacktrace: false # 是否禁止在 panic 及以上级别打印堆栈信息
  level: debug # 指定日志级别，可选值：debug, info, warn, error, dpanic, panic, fatal
  format: console # 指定日志显示格式，可选值：console, json
  output-paths: [ ./logfile.log, stdout ] # 指定日志输出位置，多个输出，用 `逗号 + 空格` 分开。stdout：标准输出，
