run:
  # 超时时间
  timeout: 5m

linters:
  # 启用所有 linters
  enable-all: true
  # 禁用部分 linters
  disable:
    - gochecknoglobals
    - gomnd
    - maligned

issues:
  # 排除指定文件的 lint 问题
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
    - path: internal/testings/.*\.go
      linters:
        - gomnd
    - path: base/example/grpc/.*\.go
      linters:
        - typecheck
    - path: interactive/integration/interactive_svc_test.go
      linters:
        - typecheck
    - path: wire_gen.go
      linters:
          - typecheck
    - path: interactive/integration/startup/wire_gen.go
      linters:
        - typecheck
    - path: interactive/wire_gen.go
      linters:
        - typecheck