// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	note3 "TestCopilot/TestEngine/internal/events/note"
	"TestCopilot/TestEngine/internal/repository"
	"TestCopilot/TestEngine/internal/repository/cache"
	"TestCopilot/TestEngine/internal/repository/dao"
	"TestCopilot/TestEngine/internal/repository/dao/note"
	note2 "TestCopilot/TestEngine/internal/repository/note"
	"TestCopilot/TestEngine/internal/service"
	"TestCopilot/TestEngine/internal/service/core/model"
	"TestCopilot/TestEngine/internal/web"
	"TestCopilot/TestEngine/internal/web/jwt"
	"TestCopilot/TestEngine/ioc"
	"github.com/google/wire"
)

import (
	_ "github.com/spf13/viper/remote"
	_ "go.uber.org/zap"
	_ "gorm.io/driver/mysql"
)

// Injectors from wire.go:

func InitWebServer() *App {
	cmdable := ioc.InitRedis()
	loggerV1 := ioc.InitLogger()
	handler := jwt.NewRedisJWTHandler(cmdable)
	v := ioc.InitMiddleware(cmdable, loggerV1, handler)
	aiHandler := web.NewAIHandler(loggerV1)
	db := ioc.InitDB(loggerV1)
	userDAO := dao.NewUserDAO(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache, loggerV1)
	userService := service.NewUserService(userRepository, loggerV1)
	userHandler := web.NewUserHandler(userService, loggerV1, handler)
	apidao := dao.NewAPIDAO(loggerV1, db)
	apiRepository := repository.NewAPIRepository(apidao, loggerV1, userRepository)
	apiService := service.NewAPIService(apiRepository, loggerV1)
	taskDAO := dao.NewGORMTaskDAO(db, loggerV1)
	taskRepository := repository.NewCacheTaskRepository(taskDAO, loggerV1, userRepository, apiRepository)
	taskService := model.NewTaskService(taskRepository, loggerV1)
	apiHandler := web.NewAPIHandler(apiService, taskService, userService, loggerV1)
	taskHandler := web.NewTaskHandler(loggerV1, taskService, userService)
	noteDAO := note.NewNoteDAO(loggerV1, db)
	authorDAO := note.NewNoteAuthorDAO(loggerV1, db)
	readerDAO := note.NewNoteReaderDAO(loggerV1, db)
	noteRepository := note2.NewNoteRepository(noteDAO, authorDAO, readerDAO, loggerV1)
	client := ioc.InitKafka()
	syncProducer := ioc.NewSyncProducer(client)
	producer := note3.NewKafkaProducer(syncProducer)
	noteService := service.NewNoteService(noteRepository, loggerV1, producer)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, loggerV1)
	interactiveService := service.NewInteractiveService(interactiveRepository, loggerV1)
	noteHandler := web.NewNoteHandler(noteService, loggerV1, interactiveService)
	engine := ioc.InitWebServer(v, aiHandler, userHandler, apiHandler, taskHandler, noteHandler)
	interactiveReadEventBatchConsumer := note3.NewInteractiveReadEventBatchConsumer(client, interactiveRepository, loggerV1)
	v2 := ioc.NewConsumers(interactiveReadEventBatchConsumer)
	rankingService := service.NewBatchRankingService(noteService, interactiveService)
	rankingJob := ioc.InitRankingJob(rankingService)
	cron := ioc.InitJobs(loggerV1, rankingJob)
	app := &App{
		server:    engine,
		consumers: v2,
		cron:      cron,
	}
	return app
}

// wire.go:

var rankingServiceSet = wire.NewSet(repository.NewCacheRankingRepository, cache.NewRankingRedisCache, service.NewBatchRankingService)
