apiVersion: v1
kind: Service
metadata:
  name: coreengine-mysql
spec:
  selector:
    app: coreengine-mysql
  ports:
    - protocol: TCP
      port: 11309 # LoadBalancer 模式，访问的端口
      targetPort: 3306 # k8s 内部通信
      nodePort: 30002 # NodePort 模式，访问的端口
  type: NodePort
  